Step4 to master
rodrigohsb/chuck-norris-facts pull request #4
Opened 2018-03-07 15:13 UTC by rodrigohsb

- Providing viewmodel dependency from DI
- View Model unit tests

2018-03-07 18:51 UTC, ubiratansoares approved these changes

2018-03-09 18:26 UTC, ubiratansoares requested changes

2018-03-09 18:26 UTC, ubiratansoares commented on app/src/main/java/br/com/chucknorrisfacts/home/viewmodel/HomeViewModel.kt
> +                    homeStatus.value = HomeStatus.Sucess(it)
Essa subscrição no fluxo deveria estar na layer de visão ....

Recomendo fazer essa alteração e fazer a API pública do ViewModel retornar um tipo reativo (Single, Observable, etc) para a layer de visão

2018-03-19 20:39 UTC, rodrigohsb commented on app/src/test/java/br/com/chucknorrisfacts/ViewModelTest.kt
> +        assertTrue((values.size == 2)
Não gostei dessa forma não mas foi o único jeito que consegui...
tava tentando assim mas não sei pq não funcionou:

testObserver
        .assertComplete()
        .assertNoErrors()
        .assertValue { status -> status is State.Success }
        .isTerminated

O lado bom de como ficou é que eu posso testar se o "Loading" veio primeiro.

2018-03-19 20:48 UTC, rodrigohsb commented on app/src/main/java/br/com/chucknorrisfacts/home/viewmodel/HomeViewModel.kt
> +                .compose(StateHandler())
Tentei fazer como se eles colaborador viesse por DI mas não conseguir rodar os testes por nada...aí tive que instanciar ele aí =/

2018-03-20 13:52 UTC, ubiratansoares approved these changes

2018-03-20 14:00 UTC, closed without merging