Step5 to Master
rodrigohsb/chuck-norris-facts pull request #5
Opened 2018-03-20 19:48 UTC by rodrigohsb

1. Removing behavior interfaces and layouts
2. Removing BaseActivity

3. Removing passive view :penguin:

4. Adding error text into string.xml file

5. Adding retry button when appropriate

6. Improved Robot UI Tests
6.1. WaitingFor Input
6.2. Success
6.3. BadRequest
6.4. EmptyState (No data)
6.5. GenericError
6.6. ClientError(4xx error)
6.7. ServerError(5xx error)
6.8. Timeout
6.9. NoConnection

2018-03-21 14:03 UTC, ubiratansoares requested changes
Estou trabalhando com todos do time, PRs com mais de 20 files e/ou 400 linhas alteradas devem ter uma documentação compreensiva explicando para o revisor o que foi feito

2018-03-21 16:04 UTC, ubiratansoares requested changes
Deixei comentários

2018-03-21 16:04 UTC, ubiratansoares commented on app/src/androidTest/java/br/com/chucknorrisfacts/home/HomeActivityBadRequestTest.kt
> +            isSuccess()
Não sei se entendi, esse teste é para verificar o erro ou o sucesso?

2018-03-21 16:04 UTC, ubiratansoares commented on app/src/androidTest/java/br/com/chucknorrisfacts/home/HomeActivityClientErrorTest.kt
> +        } withClientError {
Por qual motivo os testes de vários cenários estão em classes separadas de `AcceptanceTest`? Não poderiam ser todos na mesma classe?

2018-03-21 16:04 UTC, ubiratansoares commented on app/src/main/java/br/com/chucknorrisfacts/screenbehaviors/BehaviorsScreen.kt
> +interface BehaviorsScreen : EmptyState, GenericErrorView, LoadingView,
Não entendi esse protocolo. A proposta aqui é MVVM, ou MVP?

No MVVM, não tem o conceito da View passiva.

2018-03-21 17:06 UTC, rodrigohsb commented on app/src/androidTest/java/br/com/chucknorrisfacts/home/HomeActivityClientErrorTest.kt
> +        } withClientError {
Por causa do override do Kodein, pois, para cada tipo de teste, eu preciso sobrescrever a dependência. Se eu fizer isso numa classe só, ia ficar uma zona.

2018-03-21 17:06 UTC, rodrigohsb commented on app/src/androidTest/java/br/com/chucknorrisfacts/home/HomeActivityBadRequestTest.kt
> +            isSuccess()
Verifica o Erro de BadRequest. "isSuccess" é só pra saber se o teste passou com sucesso, seja erro ou acerto.

2018-03-21 17:06 UTC, rodrigohsb commented on app/src/main/java/br/com/chucknorrisfacts/screenbehaviors/BehaviorsScreen.kt
> +interface BehaviorsScreen : EmptyState, GenericErrorView, LoadingView,
Independente de qual protocolo for: MVVM, MVP, MVI, MXPTO,... em algum lugar, a view precisa saber mostrar os states, seja qual for (sucesso, loading, error, ...), e nesse caso, ela "pergunta" pro ViewModel em qual estado ele está, certo? E, para não precisar reescrever esses comportamentos em todas as views, coloquei-os na "BaseActivity" para que toda activity, que herde dela, já os ganhe.

2018-03-21 17:35 UTC, ubiratansoares commented on app/src/androidTest/java/br/com/chucknorrisfacts/home/HomeActivityBadRequestTest.kt
> +            isSuccess()
Essa API está confusa, pois BadRequest pressupõe uma condição de erro, mas a API verifica a condição de erro como "sucesso"...

2018-03-21 17:35 UTC, ubiratansoares commented on app/src/androidTest/java/br/com/chucknorrisfacts/home/HomeActivityClientErrorTest.kt
> +        } withClientError {
Isso é possível de ser feito.

2018-03-21 17:40 UTC, ubiratansoares commented on app/src/main/java/br/com/chucknorrisfacts/screenbehaviors/BehaviorsScreen.kt
> +interface BehaviorsScreen : EmptyState, GenericErrorView, LoadingView,
A Activity ("View") pergunta para o ViewModel quais são os fatos, e recebe um Observable<State>, ou seja, uma sequência de estados. Para cada estado, ela renderiza o estado. Não existe a necessidade dela ser uma View passiva, isso é um conceito do MVP.

Adicionalmente : estou reprovando esse PR (novamente) - assim como fiz com seus amigos, rs - pois a princípio, nós devemos levar como regra de ouro

> Não compartilharás código via herança

A menos que você consiga me `PROVAR` que `100%` das Activities da aplicação irão seguir BehaviorsScreen, você não deve fazer essa lógica ser compartilhada via herança. Caso contrário, você deve favorecer a composição, e pensar em estratégias componíveis para abstrair eventuais repetições na lógica de UI

2018-03-23 02:44 UTC, ubiratansoares approved these changes

2018-03-23 13:11 UTC, merged